### ISSUE TITLE
Internal bug: item_relative = item.relative_to(root_absolute)

### ISSUE THREAD

**Issue by amai2012** [marzer/check-cmake#4]
Running  _check-cmake 0.5.1_ by `check-cmake --recurse .` on ubuntu 24.04 from a venv triggered an exception:
~~~python
*************

You appear to have triggered an internal bug!
Please file an issue at github.com/marzer/check-cmake/issues
Many thanks!

*************

Traceback (most recent call last):
  File "/home/me/project/venv/lib/python3.12/site-packages/check_cmake/main.py", line 240, in main_impl
    check_directory(args.root)
  File "/home/me/project/venv/lib/python3.12/site-packages/check_cmake/main.py", line 169, in check_directory
    check_directory(item)
  File "/home/me/project/venv/lib/python3.12/site-packages/check_cmake/main.py", line 169, in check_directory
    check_directory(item)
  File "/home/me/project/venv/lib/python3.12/site-packages/check_cmake/main.py", line 116, in check_directory
    item_relative = item.relative_to(root_absolute)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/pathlib.py", line 682, in relative_to
    raise ValueError(f"{str(self)!r} is not in the subpath of {str(other)!r}")
ValueError: '/usr/bin/python3.12' is not in the subpath of '/home/me/project/'
~~~

**Comment by marzer** [comment]
Hmmm, interesting 🤔 . Thanks for the report, I'll look into it.

**Comment by marzer** [comment]
Sorry, finally got back to this. Fixed in [v0.5.2](https://github.com/marzer/check-cmake/releases/tag/v0.5.2), thanks again for the report 👍🏼
